name: Python tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  lint_and_tests:
    env:
      DJANGO_SETTINGS_MODULE: backend.settings.test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install requirements
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Install tools
        run: pip install flake8 pep8-naming
      - name: lint
        run: flake8 backend/
      - name: test
        run: |
          cd backend/
          coverage run manage.py test
          cd ..

